version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092"
    depends_on:
      - "zookeeper"

  php-kafka:
    build: .
    volumes:
      - .:/var/www/php-kafka
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - "kafka"
